update repository
apmath-web/clients pull request #38
Opened 2019-04-27 03:00 UTC by levozavr

rewrite methods in repository according database api
- [ ] add using application models
- [ ] add db driver
- [ ] rewrite CI
- [ ] rewrite Docker file
- [ ] error handling

2019-04-27 18:39 UTC, malinink requested changes

2019-04-27 18:39 UTC, malinink commented on Infrastructure/applicationModels/ClientApplicationModel.go
> +func (c *ClientApplicationModel) UpdateId(id int) {
updateId ?

2019-04-27 18:39 UTC, malinink commented on Infrastructure/applicationModels/ClientApplicationModel.go
> +	if err := tx.QueryRow("INSERT INTO clients "+
на будущее предлагаю всё же взглянуть на ORM, мне кажется что должен быть поприятнее код в результате перехода.

2019-04-27 18:39 UTC, malinink commented on Infrastructure/applicationModels/ClientApplicationModel.go
> +func (c *ClientApplicationModel) UpdateClient(cl Domain.ClientDomainModelInterface, tx *sql.Tx) error {
судя по коду, я бы сказал что это всё не должно напрямую касаться модели, а должно быть в репозитории. Но это мысль, а не повод для действий.

2019-04-27 18:39 UTC, malinink commented on Infrastructure/applicationModels/JobApplicationModel.go
> +func (j *JobApplicationModel) SaveJob(tx *sql.Tx) error {
они не обновляются? т.е. только добавить и удалить?

2019-04-27 18:39 UTC, malinink commented on Infrastructure/applicationModels/JobApplicationModel.go
> +func (j *JobApplicationModel) SaveJob(tx *sql.Tx) error {
странно, почему сохранение тут, а удаление в другом месте?

2019-04-27 18:42 UTC, levozavr commented on Infrastructure/applicationModels/JobApplicationModel.go
> +func (j *JobApplicationModel) SaveJob(tx *sql.Tx) error {
Просто работы могут добавляться или удаляться в процессе изменения и по-моему быстрее будет их обновлять таким образом

2019-04-27 18:43 UTC, levozavr commented on Infrastructure/applicationModels/JobApplicationModel.go
> +func (j *JobApplicationModel) SaveJob(tx *sql.Tx) error {
а там удаление сразу всех работ связанных с этим клиентом

2019-04-27 20:46 UTC, levozavr commented on Infrastructure/applicationModels/JobApplicationModel.go
> +func (j *JobApplicationModel) SaveJob(tx *sql.Tx) error {
Я переделал это, теперь удаление на месте

2019-04-28 19:16 UTC, malinink approved these changes

2019-04-28 19:16 UTC, merged